name: CI of mc_udp

on:
  push:
    paths-ignore:
      # Changes to those files don't mandate running CI
      - ".github/workflows/package.yml"
      - "debian/**"
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  clang-format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install clang-format-10
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install clang-format-10
    - name: Run clang-format-check
      run: |
        ./.clang-format-check.sh
  build:
    needs: clang-format
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        compiler: [gcc,clang]
        build-type: [Release, RelWithDebInfo]
        exclude:
          # Only default compiler on macos-latest and windows-latest
          - os: macos-latest
            compiler: clang
          - os: windows-latest
            compiler: clang
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Temporary APT mirrors cleanup
      if: startsWith(runner.os, 'Linux')
      run: |
        set -e
        sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list
    - name: Setup extra APT mirror
      if: startsWith(runner.os, 'Linux')
      run: |
        set -x
        set -e
        curl -1sLf 'https://dl.cloudsmith.io/public/mc-rtc/head/setup.deb.sh' | sudo -E bash
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: cython python-setuptools cython3 python3-setuptools python-dev python3-dev libpython2.7-dev libpython3-dev hrpsys-base libmc-rtc-dev
        macos: |
          brew-taps: mc-rtc/mc-rtc
          brew: mc_rtc
          pip: Cython
        windows: |
          pip: Cython
          options: -DPYTHON_BINDING:BOOL=OFF
          github:
            - path: eigenteam/eigen-git-mirror
              ref: 3.3.7
            - path: leethomason/tinyxml2
              ref: 7.1.0
            - path: libgeos/geos
              ref: 3.8.1
              options: -DBUILD_TESTING:BOOL=ON
            - path: nanomsg/nanomsg
              ref: 1.1.5
            - path: jbeder/yaml-cpp
              ref: 29dcf92f870ee51cce8d68f8fcfe228942e8dfe1
              options: -DYAML_CPP_BUILD_TESTS:BOOL=OFF
            - path: gabime/spdlog
              ref: v1.6.1
              options: -DSPDLOG_BUILD_EXAMPLE:BOOL=OFF -DSPDLOG_BUILD_SHARED:BOOL=ON
            - path: loco-3d/ndcurves
              ref: v1.1.2
              options: -DBUILD_PYTHON_INTERFACE:BOOL=OFF
            - path: jrl-umi3218/SpaceVecAlg
            - path: jrl-umi3218/sch-core
            - path: jrl-umi3218/eigen-qld
            - path: jrl-umi3218/eigen-quadprog
            - path: jrl-umi3218/RBDyn
            - path: jrl-umi3218/Tasks
            - path: jrl-umi3218/tvm
              options: -DTVM_WITH_ROBOT:BOOL=OFF
            - path: jrl-umi3218/state-observation
            - path: jrl-umi3218/mc_rbdyn_urdf
            - path: jrl-umi3218/mc_rtc_data
            - path: jrl-umi3218/mc_rtc
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        options: -DBUILD_DUMMY_SERVER:BOOL=ON -DBUILD_DUMMY_CLIENT:BOOL=ON
        linux-options: -DPYTHON_BINDING_BUILD_PYTHON2_AND_PYTHON3:BOOL=ON
        macos-options: -DBUILD_OPENRTM_SERVER:BOOL=OFF
        windows-options: -DBUILD_OPENRTM_SERVER:BOOL=OFF
    - name: Slack Notification
      if: failure()
      uses: archive/github-actions-slack@master
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack-channel: '#ci'
        slack-text: >
          [mc_udp] Build *${{ matrix.os }}/${{ matrix.build-type }} (${{ matrix.compiler }})* failed on ${{ github.ref }}
